In [ ]:
import numpy as np

In [ ]:
from numpy import *

In [ ]:
a = np.zeros(5)
a

In [ ]:
a = zeros(5)
a

In [ ]:
a = zeros([5,3])
a

In [ ]:
lst = []
lst.append(1)
lst

In [ ]:
lst.append(2)
lst

In [ ]:
inx = [0,0,0,0,1,0,1,1]

In [ ]:
data = [[0, 0, 0, 0, 1, 0, 1, 1],
       [0, 0, 1, 1, 1, 0, 1, 1],
       [0, 0, 0, 1, 1, 0, 1, 1],
       [0, 0, 0, 0, 1, 0, 1, 1],
       [0, 0, 1, 0, 1, 0, 1, 1],
       [0, 0, 1, 0, 1, 0, 1, 1],
       [0, 1, 0, 0, 1, 0, 1, 1],
       [0, 0, 0, 0, 1, 0, 1, 1]]

In [ ]:
data1 = tile(inx, (8, 1))
data1

In [ ]:
diffMat = data1 - data
diffMat

In [ ]:
sqDiffMat = diffMat ** 2
sqDiffMat

In [ ]:
sqDistances = sqDiffMat.sum(axis=1)
sqDistances

In [ ]:
distances = sqDistances ** 0.5
distances

In [ ]:
sortedDistIndicies = distances.argsort()
sortedDistIndicies

In [ ]:
print("hah ", [0, 3, 7, 2, 4, 5, 6, 1])

In [ ]:
np.random.rand(2,4)

In [ ]:
np.random.rand(4,2)

In [ ]:
# sum

w = [1,2]
w = np.array(w)
x = np.random.rand(4,2)
print(x)
print(w*x)
print(np.dot(w,x.T))
np.sum(w*x,axis=1)

In [ ]:
# sign
np.sign(-1),np.sign(2)

In [32]:
import numpy as np
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
c = np.array([6, 7, 8])
np.column_stack((a, b, c))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [ ]:
np.row_stack((a, b, c))

In [33]:
a = np.array([[1,2], [3,4],[5,6]])
b = np.array([5,6,7])
np.column_stack((a, b))

array([[1, 2, 5],
       [3, 4, 6],
       [5, 6, 7]])

In [ ]:
w = [1,2]
w = np.array(w)
w[...,0],w[0]

In [ ]:
x = np.linspace(0, 20, 500)
x.T.shape

# 矩阵乘法

In [29]:
# dot

import numpy as np
a = np.arange(1,5).reshape(2,2)
b = np.arange(5,9).reshape(2,2)
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [ ]:
np.dot(a,b)

In [ ]:
np.dot(a,a)

In [ ]:
a

In [31]:
a**2

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [ ]:
a.T

In [ ]:
np.dot(a,a.T)

In [30]:
a*a

array([[ 1,  4],
       [ 9, 16]])

In [22]:
np.multiply(a,a)

array([[ 1,  4],
       [ 9, 16]])

In [24]:
"1"+ bytes(2)

TypeError: can only concatenate str (not "bytes") to str

In [26]:
str = '你的分数是:'
num = 82
num = str(num)
text = str+num+'分 | 琼台博客'
text

TypeError: 'str' object is not callable

In [28]:
"dd%s"%2

'dd2'