In [1]:
import numpy as np

In [2]:
from numpy import *

In [8]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [11]:
a = zeros(5)
a

array([0., 0., 0., 0., 0.])

In [14]:
a = zeros([5,3])
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
lst = []
lst.append(1)
lst

[1]

In [23]:
lst.append(2)
lst

[1, 2, 2]

In [27]:
inx = [0,0,0,0,1,0,1,1]

In [36]:
data = [[0, 0, 0, 0, 1, 0, 1, 1],
       [0, 0, 1, 1, 1, 0, 1, 1],
       [0, 0, 0, 1, 1, 0, 1, 1],
       [0, 0, 0, 0, 1, 0, 1, 1],
       [0, 0, 1, 0, 1, 0, 1, 1],
       [0, 0, 1, 0, 1, 0, 1, 1],
       [0, 1, 0, 0, 1, 0, 1, 1],
       [0, 0, 0, 0, 1, 0, 1, 1]]

In [37]:
data1 = tile(inx, (8, 1))
data1

array([[0, 0, 0, 0, 1, 0, 1, 1],
       [0, 0, 0, 0, 1, 0, 1, 1],
       [0, 0, 0, 0, 1, 0, 1, 1],
       [0, 0, 0, 0, 1, 0, 1, 1],
       [0, 0, 0, 0, 1, 0, 1, 1],
       [0, 0, 0, 0, 1, 0, 1, 1],
       [0, 0, 0, 0, 1, 0, 1, 1],
       [0, 0, 0, 0, 1, 0, 1, 1]])

In [38]:
diffMat = data1 - data
diffMat

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, -1, -1,  0,  0,  0,  0],
       [ 0,  0,  0, -1,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, -1,  0,  0,  0,  0,  0],
       [ 0,  0, -1,  0,  0,  0,  0,  0],
       [ 0, -1,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [39]:
sqDiffMat = diffMat ** 2
sqDiffMat

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [40]:
sqDistances = sqDiffMat.sum(axis=1)
sqDistances

array([0, 2, 1, 0, 1, 1, 1, 0], dtype=int32)

In [41]:
distances = sqDistances ** 0.5
distances

array([0.        , 1.41421356, 1.        , 0.        , 1.        ,
       1.        , 1.        , 0.        ])

In [42]:
sortedDistIndicies = distances.argsort()
sortedDistIndicies

array([0, 3, 7, 2, 4, 5, 6, 1], dtype=int64)

In [43]:
print("hah ", [0, 3, 7, 2, 4, 5, 6, 1])

hah  [0, 3, 7, 2, 4, 5, 6, 1]


In [3]:
np.random.rand(2,4)

array([[0.35183254, 0.26692174, 0.63521111, 0.18971146],
       [0.17114539, 0.68867136, 0.0073911 , 0.13935938]])

In [7]:
np.random.rand(4,2)

array([[0.30783692, 0.84612147],
       [0.5789359 , 0.5516744 ],
       [0.5956411 , 0.58327901],
       [0.83281469, 0.84636563]])

In [34]:
# sum

w = [1,2]
w = np.array(w)
x = np.random.rand(4,2)
print(x)
print(w*x)
print(np.dot(w,x.T))
np.sum(w*x,axis=1)

[[0.6165323  0.84477139]
 [0.60967328 0.74263174]
 [0.20267583 0.96311516]
 [0.19083418 0.98351866]]
[[0.6165323  1.68954278]
 [0.60967328 1.48526348]
 [0.20267583 1.92623033]
 [0.19083418 1.96703732]]
[2.30607508 2.09493676 2.12890616 2.15787151]


array([2.30607508, 2.09493676, 2.12890616, 2.15787151])

In [17]:
# sign
np.sign(-1),np.sign(2)

(-1, 1)

In [18]:
import numpy as np
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
c = np.array([6, 7, 8])
np.column_stack((a, b, c))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [19]:
np.row_stack((a, b, c))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
a = np.array([[1,2], [3,4],[5,6]])
b = np.array([5,6,7])
np.column_stack((a, b))

array([[1, 2, 5],
       [3, 4, 6],
       [5, 6, 7]])

In [28]:
w = [1,2]
w = np.array(w)
w[...,0],w[0]

(array(1), 1)

In [32]:
x = np.linspace(0, 20, 500)
x.T.shape

(500,)