In [4]:
# 示例代码
import tensorflow as tf
import numpy as np
sess = tf.InteractiveSession()

D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py:1714: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [5]:
np.identity(5,dtype=np.int32)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [6]:
keep_prob = tf.placeholder(tf.float32)
embedding = tf.Variable(np.identity(5,dtype=np.float32))
input_ids = tf.placeholder(dtype=tf.int32,shape=[None])
input_embedding = tf.nn.embedding_lookup(embedding,input_ids)
inputs = tf.nn.dropout(input_embedding, keep_prob=keep_prob)

In [7]:
sess.run(tf.initialize_all_variables())

Instructions for updating:
Use `tf.global_variables_initializer` instead.


In [8]:
print(sess.run(embedding))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
sss = sess.run(input_embedding,feed_dict={input_ids:[0,1,2,3,2,1,0]})
sss

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.]], dtype=float32)

In [15]:
tf.get_variable_scope().reuse_variables()
inputs1 = sess.run(inputs,feed_dict={input_ids:[0,0,0,0],keep_prob:0.5})
inputs1

array([[2., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0.]], dtype=float32)

In [26]:
  t1 = [[[11, 12, 13],[14,15,16]], [[24, 25, 26], [27,28,29]]]
  t2 = [[[37, 38, 39],[31,32,33]], [[41, 42,43],[44,45,46]]]
  tf.concat([t1, t2], 0)  # [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
 
  # tensor t3 with shape [2, 3]
  # tensor t4 with shape [2, 3]
  #tf.shape(tf.concat([t3, t4], 0))  # [4, 3]
  #tf.shape(tf.concat([t3, t4], 1))  # [2, 6]


<tf.Tensor 'concat_12:0' shape=(4, 2, 3) dtype=int32>

In [27]:
t1,t2

([[[11, 12, 13], [14, 15, 16]], [[24, 25, 26], [27, 28, 29]]],
 [[[37, 38, 39], [31, 32, 33]], [[41, 42, 43], [44, 45, 46]]])

In [25]:
sess.run(tf.concat([t1, t2], 1))  # [[1, 2, 3, 7, 8, 9], [4, 5, 6, 10, 11, 12]]

array([[[11, 12, 13],
        [14, 15, 16],
        [37, 38, 39],
        [31, 32, 33]],

       [[24, 25, 26],
        [27, 28, 29],
        [41, 42, 43],
        [44, 45, 46]]])

In [30]:
sess.run(tf.reshape(tf.concat([t1, t2], 1),[-1,3]))

array([[11, 12, 13],
       [14, 15, 16],
       [37, 38, 39],
       [31, 32, 33],
       [24, 25, 26],
       [27, 28, 29],
       [41, 42, 43],
       [44, 45, 46]])